### ISSUE TITLE
Crashing at Peep

### ISSUE THREAD

**Issue by acmfan** [networkMe/missinghud2#10]
As soon as I start Peep's first eye dislodges, the game (Isaac Rebirth) crashes. This is independent of items, or where Peep is fought. Bloat works well, however. It is the latest update of TBoI:R.

**Comment by 40163650** [comment]
I don't see how this program could crash rebirth like that, do you have any other mods installed?

**Comment by acmfan** [comment]
No, there is 0 other mods installed. I'm also on Windows 10.
I re-installed rebirth, and tried again, opening rebirth, then the missinghud file. I did a speedrun in order to get to the boss rush. Once there, I fought until getting to the wave with Peep, and as soon as Peep got damaged enough to dislocate an eye, the game promptly crashed

**Comment by 40163650** [comment]
Which version are you using?

**Comment by acmfan** [comment]
I am using version 1.2.4

**Comment by 40163650** [comment]
Try using 1.2.1

**Comment by acmfan** [comment]
It crashed at 1.2.1 as well. When I choose continue from the menu on a run where it has crashed, it starts me at the start of the floor

**Comment by networkMe** [comment]
I'm not going to lie, that is the weirdest thing I have ever heard (given you are on the latest Rebirth from Steam).
MHUD2 doesn't touch anything to do with bosses and the fact it only happens when his eye pops is even weirder. I'm going to assume if you leave MHUD2 off, you can fight Peep fine?

The only thing I can imagine it would be is that MHUD2 reads from a bad memory address for some unknown reason on your computer. Can you post what the MHUD2.log says (on 1.2.4)?

**Comment by acmfan** [comment]
It seems like it crashes in general when fighting Peep.
I am sorry for having taken up some of your time.
Thank you for your support, however.

**Comment by networkMe** [comment]
It sounds like you have a leftover mod or something corrupting your assets files so when it tries to load the popped out eye, it crashes. Maybe try a Steam files verification?

I'm going to close this as it's unrelated to MHUD2
